apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: passport

resources:
  - kubernetes/passports.k8s.passport-pro.ai-v1.yml
  - kubernetes/passportrealmimports.k8s.passport-pro.ai-v1.yml
  - kubernetes/kubernetes.yml